import { mkdtemp, readFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import type { AppSpecV1 } from '../src/appspec.js'
import { generateCrudLayer, writeCrudLayer } from '../src/crud-generator.js'

const roots:string[]=[]
afterEach(async()=>Promise.all(roots.splice(0).map(root=>rm(root,{recursive:true,force:true}))))
const spec:AppSpecV1={schema_version:1,problem:'Gerenciar clientes e próximas tarefas.',audience:'Equipe',journeys:['Criar, editar e excluir clientes'],pages:[{name:'Clientes',sections:['Gestão']}],entities:[{name:'Cliente',kind:'database',sensitive:false,fields:[{name:'Nome',type:'text',required:true},{name:'Status',type:'selection',required:true,options:['Novo','Atendido']},{name:'Ativo',type:'boolean',required:true},{name:'Limite',type:'number',required:false},{name:'Data',type:'date',required:false},{name:'E-mail',type:'email',required:false},{name:'Telefone',type:'phone',required:false}]}],sensitive_data:{detected:[],confirmed_by_user:false},accessibility:{wcag_level:'AA',keyboard_required:true,reduced_motion:true},language:'pt-BR',acceptance_criteria:['A equipe gerencia clientes.']}
describe('generated CRUD panel',()=>{
  it('generates authenticated create, edit and confirmed delete controls',()=>{const layer=generateCrudLayer(spec,'crud-panel');expect(layer.files.map(file=>file.path)).toEqual(['src/components/generated/confirm-delete-button.tsx','src/server/actions/cliente.ts','src/components/generated/cliente-panel.tsx','src/components/generated/index.ts']);const joined=layer.files.map(file=>file.content).join('\n');expect(joined).toContain('requireFormSession');expect(joined).toContain('Salvar alterações');expect(joined).toContain('window.confirm("Tem certeza de que deseja excluir este item?")');expect(joined).toContain('data-testid="cliente-create-form"');expect(generateCrudLayer(spec,'catalog')).toEqual({files:[],protectedPaths:[]})})
  it('writes protected paths once',async()=>{const root=await mkdtemp(join(tmpdir(),'dz23-crud-'));roots.push(root);const layer=generateCrudLayer(spec,'crud-panel');await writeCrudLayer(root,layer);await expect(readFile(resolve(root,'src/server/actions/cliente.ts'),'utf8')).resolves.toContain('deleteCliente');await expect(writeCrudLayer(root,layer)).rejects.toMatchObject({code:'EEXIST'})})
  it('generates a safe relation selector, validates on the server and translates restricted deletion',()=>{const linked:AppSpecV1={...spec,entities:[{name:'Cliente',kind:'database',sensitive:false,fields:[{name:'Nome',type:'text',required:true},{name:'Dono',type:'reference',required:false,reference_entity:'Cliente'}]}]};const layer=generateCrudLayer(linked,'crud-panel');const joined=layer.files.map(file=>file.content).join('\n');expect(joined).toContain('donoOptions.map');expect(joined).toContain('new ClienteRepository(database).get(reference_dono)');expect(joined).toContain('FOREIGN KEY constraint failed');expect(joined).toContain('Não é possível excluir este item porque ele é usado por outro cadastro.')})
})
