import { mkdtemp, mkdir, readFile, rm, symlink, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { afterEach, describe, expect, it, vi } from 'vitest'
import type { AppSpecV1 } from '../src/appspec.js'
import { createDesignSpec } from '../src/design.js'
import type { StudioPlan, StudioRun } from '../src/model.js'
import { PromptToAppPipeline, type CodeGeneratorPort } from '../src/pipeline.js'
import { hashTree, PREVIEW_ARTIFACT_RELATIVE_PATH, type ContainerBuilder } from '../src/runner.js'
import { PromptToAppError, type PromptToAppActor, type PromptToAppService } from '../src/service.js'

const actor: PromptToAppActor = { userId: 'owner', orgId: 'org-a', tenantId: 'tenant-a', role: 'owner' }
const spec: AppSpecV1 = {
  schema_version: 1, problem: 'Apresentar serviços.', audience: 'Clientes', journeys: ['Conhecer serviços'],
  pages: [{ name: 'Início', sections: ['Serviços'] }], entities: [], sensitive_data: { detected: [], confirmed_by_user: false },
  accessibility: { wcag_level: 'AA', keyboard_required: true, reduced_motion: true }, language: 'pt-BR',
  acceptance_criteria: ['A página tem um título.'],
}
const plan: StudioPlan = {
  plan_id: 'plan', spec_id: 'spec', project_id: 'project', org_id: actor.orgId, tenant_id: actor.tenantId,
  slices: [{ slice_id: 'slice', title: 'Página', description: 'Criar página', acceptance_criteria: ['Compila'], planned_files: ['content/app.json', 'src/GeneratedApp.tsx'] }],
  status: 'APPROVED', created_at: '2026-09-03T12:00:00.000Z', updated_at: '2026-09-03T12:00:00.000Z',
}
const cleanGeneration = {
  files: [
    { path: 'content/app.json', content: '{"title":"Aurora","description":"Serviços"}' },
    { path: 'src/GeneratedApp.tsx', content: 'export default function GeneratedApp(){ return <main><h1>Início</h1><h2>Serviços</h2></main> }' },
  ], route: 'ollama', model: 'qwen', inputTokens: 10, outputTokens: 20,
} as const
const roots: string[] = []
afterEach(async () => Promise.all(roots.splice(0).map(root => rm(root, { recursive: true, force: true }))))

async function fixture(options: { readonly preflight?: 'OK' | 'BLOCKED_EXTERNAL'; readonly execute?: (directory: string, command: string) => Promise<{ exitCode: number; stdout: string; stderr: string; timedOut: boolean }> } = {}) {
  const root = await mkdtemp(join(tmpdir(), 'dz23-pipeline-test-')); roots.push(root)
  const templateDirectory = resolve(root, 'template'); const runsRoot = resolve(root, 'runs')
  await mkdir(resolve(templateDirectory, 'src'), { recursive: true })
  await writeFile(resolve(templateDirectory, 'package.json'), '{"private":true}')
  await writeFile(resolve(templateDirectory, 'src/App.tsx'), 'export default function App(){ return null }')
  await writeFile(resolve(templateDirectory, 'next-env.d.ts'), '/// generated by Next.js')
  let state = 'PLAN_APPROVED'
  const runs: StudioRun[] = []; const transitions: string[] = []; const evidence: unknown[] = []
  const service = {
    project: vi.fn(() => ({ state, category: 'landing-page' })), plan: vi.fn(() => plan), latestSpec: vi.fn(() => ({ app_spec: spec })),
    designOrDefault: vi.fn(() => createDesignSpec({ preset: 'modern' })),
    transition: vi.fn(async (_actor, _projectId, to: string) => { state = to; transitions.push(to); return { state } }),
    putRun: vi.fn(async (_actor, run: StudioRun) => { runs.push(run) }),
    putEvidence: vi.fn(async (_actor, item: unknown) => { evidence.push(item) }),
  }
  const execute = vi.fn(options.execute ?? (async (directory: string, command: string) => {
    if (command === 'pnpm run build') await writeRuntimeOutput(directory)
    if (command === 'pnpm run test:e2e') {
      const reportPath = resolve(directory, 'evidence/appspec-report.json')
      const report = JSON.parse(await readFile(reportPath, 'utf8')) as { checks: Array<{ status: string }> }
      report.checks = report.checks.map(check => check.status === 'PENDING' ? { ...check, status: 'PASSED' } : check)
      await writeFile(reportPath, JSON.stringify(report))
    }
    return { exitCode: 0, stdout: 'ok', stderr: '', timedOut: false }
  }))
  const builder = {
    preflight: vi.fn(async () => options.preflight === 'BLOCKED_EXTERNAL'
      ? { state: 'BLOCKED_EXTERNAL' as const, message: 'Construtor indisponível.' }
      : { state: 'OK' as const, message: 'ok' }),
    execute,
  }
  let id = 0
  const pipeline = new PromptToAppPipeline({
    service: service as unknown as PromptToAppService, builder: builder as unknown as ContainerBuilder,
    templateDirectory, runsRoot, now: () => new Date('2026-09-03T12:00:00.000Z'), createId: () => `id-${++id}`,
  })
  return { pipeline, service, builder, execute, runs, transitions, evidence, templateDirectory }
}

describe('Prompt-to-App pipeline', () => {
  it('rejects a template symlink before creating a run or changing project state', async () => {
    const f = await fixture(); const outside = await mkdtemp(join(tmpdir(), 'dz23-template-outside-')); roots.push(outside)
    await symlink(outside, resolve(f.templateDirectory, 'linked'), 'dir')
    const generator = { generate: vi.fn(async () => cleanGeneration) }
    await expect(f.pipeline.run(actor, 'project', generator)).rejects.toThrow('Link simbólico')
    expect(generator.generate).not.toHaveBeenCalled()
    expect(f.runs).toEqual([])
    expect(f.transitions).toEqual([])
  })

  it('records a verified prototype only after every offline step passes', async () => {
    const f = await fixture(); const generator = { generate: vi.fn(async () => cleanGeneration) }
    const result = await f.pipeline.run(actor, 'project', generator)
    expect({ result, runs: f.runs, transitions: f.transitions }).toMatchObject({ result: { state: 'VERIFIED_PROTOTYPE', attempts: 1 } })
    expect(f.transitions).toEqual(['GENERATING', 'BUILD_OK', 'TESTS_OK', 'VERIFIED_PROTOTYPE'])
    expect(f.execute).toHaveBeenCalledTimes(4)
    expect(f.runs.at(-1)).toMatchObject({ stage: 'verify', state: 'PASSED', route: 'ollama', input_tokens: 10, output_tokens: 20, failure_code: null })
    expect(result.runDirectory).toBeDefined()
    const passedRun = f.runs.at(-1)
    expect(passedRun?.artifact_sha256).toMatch(/^[a-f0-9]{64}$/u)
    const artifactPath = resolve(result.runDirectory!, PREVIEW_ARTIFACT_RELATIVE_PATH)
    expect(passedRun?.artifact_sha256).toBe(await hashTree(artifactPath))
    expect(f.runs.filter(run => run.state !== 'PASSED').every(run => run.artifact_sha256 == null)).toBe(true)
    await writeFile(resolve(artifactPath, '.next/standalone/server.js'), 'tampered')
    expect(await hashTree(artifactPath)).not.toBe(passedRun?.artifact_sha256)
    expect(f.runs.at(-1)?.acceptance_checks.filter(check => check.status === 'PASSED').length).toBeGreaterThanOrEqual(4)
    expect(f.runs.at(-1)?.acceptance_checks).toContainEqual(expect.objectContaining({ kind: 'criterion', status: 'NOT_AUTOMATED' }))
    expect(f.runs.at(-1)).toMatchObject({ operation_id: expect.any(String), owner_session_id: 'direct-execution' })
    expect(f.evidence).toHaveLength(2)
  })

  it.each([
    ['missing checks', '{}'],
    ['invalid JSON', '{'],
    ['empty checks', '{"schema_version":1,"checks":[]}'],
  ])('fails closed when the AppSpec report has %s', async (_case, content) => {
    const f = await fixture({ execute: async (directory, command) => {
      if (command === 'pnpm run test:e2e') await writeFile(resolve(directory, 'evidence/appspec-report.json'), content)
      return { exitCode: 0, stdout: 'ok', stderr: '', timedOut: false }
    } })
    await expect(f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })).resolves.toMatchObject({ state: 'TESTS_FAILED' })
    expect(f.runs.some(run => run.state === 'PASSED')).toBe(false)
    expect(f.transitions).not.toContain('VERIFIED_PROTOTYPE')
    expect(f.runs.at(-1)).toMatchObject({ state: 'FAILED', failure_code: 'APPSPEC_REPORT_INVALID' })
  })

  it('terminalizes the run and project when artifact materialization fails', async () => {
    const f = await fixture({ execute: async (directory, command) => {
      if (command === 'pnpm run test:e2e') await passAcceptance(directory)
      return { exitCode: 0, stdout: 'ok', stderr: '', timedOut: false }
    } })
    await expect(f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })).resolves.toMatchObject({ state: 'BUILD_FAILED', attempts: 1 })
    expect(f.runs.at(-1)).toMatchObject({ state: 'FAILED', failure_code: 'ARTIFACT_MATERIALIZATION_FAILED', artifact_sha256: null })
    expect(f.transitions).toEqual(['GENERATING', 'BUILD_FAILED'])
    expect(f.service.project()).toMatchObject({ state: 'BUILD_FAILED' })
  })

  it('terminalizes an unexpected test-process failure without leaving GENERATING', async () => {
    const f = await fixture({ execute: async (directory, command) => {
      if (command === 'pnpm run build') await writeRuntimeOutput(directory)
      if (command === 'pnpm run test') throw new Error('subprocess-channel-lost')
      return { exitCode: 0, stdout: 'ok', stderr: '', timedOut: false }
    } })
    await expect(f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })).resolves.toMatchObject({ state: 'TESTS_FAILED' })
    expect(f.runs.at(-1)).toMatchObject({ state: 'FAILED', stage: 'test', failure_code: 'PIPELINE_UNEXPECTED_FAILURE' })
    expect(f.transitions).toEqual(['GENERATING', 'BUILD_OK', 'TESTS_FAILED'])
  })

  it('interrupts a verified attempt if mandatory evidence cannot be persisted', async () => {
    const f = await fixture()
    f.service.putEvidence.mockRejectedValueOnce(new Error('storage-unavailable'))
    await expect(f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })).resolves.toMatchObject({ state: 'INTERRUPTED' })
    expect(f.runs.at(-1)).toMatchObject({ state: 'FAILED', stage: 'verify', failure_code: 'PIPELINE_UNEXPECTED_FAILURE', artifact_sha256: null })
    expect(f.transitions).toEqual(['GENERATING', 'INTERRUPTED'])
    expect(f.transitions).not.toContain('VERIFIED_PROTOTYPE')
  })

  it('rejects an oversized acceptance report before parsing it', async () => {
    const f = await fixture({ execute: async (directory, command) => {
      if (command === 'pnpm run test:e2e') await writeFile(resolve(directory, 'evidence/appspec-report.json'), ' '.repeat(1024 * 1024 + 1))
      return { exitCode: 0, stdout: 'ok', stderr: '', timedOut: false }
    } })
    await expect(f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })).resolves.toMatchObject({ state: 'TESTS_FAILED' })
    expect(f.runs.at(-1)).toMatchObject({ state: 'FAILED', failure_code: 'APPSPEC_REPORT_TOO_LARGE' })
  })

  it('does not retry a process that exceeds the output budget', async () => {
    const f = await fixture({ execute: async () => ({
      exitCode: -1, stdout: 'bounded', stderr: '', timedOut: false,
      terminationReason: 'output_limit' as const, outputLimitExceeded: true,
    }) })
    await expect(f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })).resolves.toMatchObject({ state: 'BUILD_FAILED', attempts: 1 })
    expect(f.execute).toHaveBeenCalledTimes(1)
    expect(f.runs.at(-1)).toMatchObject({ state: 'FAILED', failure_code: 'PROCESS_OUTPUT_LIMIT_EXCEEDED' })
  })

  it('allows only the framework-generated next-env file to change during build', async () => {
    const f = await fixture({ execute: async (directory, command) => {
      if (command === 'pnpm run build') { await writeRuntimeOutput(directory); await writeFile(resolve(directory, 'next-env.d.ts'), '/// regenerated by Next.js') }
      if (command === 'pnpm run test:e2e') await passAcceptance(directory)
      return { exitCode: 0, stdout: 'ok', stderr: '', timedOut: false }
    } })
    await expect(f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })).resolves.toMatchObject({ state: 'VERIFIED_PROTOTYPE' })
  })

  it('rejects a build that changes another protected template file', async () => {
    const f = await fixture({ execute: async (directory, command) => {
      if (command === 'pnpm run build') { await writeRuntimeOutput(directory); await writeFile(resolve(directory, 'src/App.tsx'), 'tampered') }
      if (command === 'pnpm run test:e2e') await passAcceptance(directory)
      return { exitCode: 0, stdout: 'ok', stderr: '', timedOut: false }
    } })
    await expect(f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })).resolves.toMatchObject({ state: 'BUILD_FAILED', message: 'TEMPLATE_INTEGRITY_FAILED' })
  })

  it('distinguishes a test failure from a build failure after three attempts', async () => {
    const f = await fixture({ execute: async (_directory, command) => ({ exitCode: command === 'pnpm run test' ? 1 : 0, stdout: '', stderr: '', timedOut: false }) })
    const result = await f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })
    expect(result).toMatchObject({ state: 'TESTS_FAILED', attempts: 3 })
    expect(f.transitions).toEqual(['GENERATING', 'BUILD_OK', 'TESTS_FAILED'])
    const failures = f.runs.filter(run => run.state === 'FAILED')
    expect(failures).toHaveLength(3)
    expect(failures.every(run => run.stage === 'test' && run.failure_code === 'pnpm run test: exit 1')).toBe(true)
    expect(failures.every(run => run.artifact_sha256 == null)).toBe(true)
  })

  it('retries rejected model output with the prior diagnostic and closes as build failed', async () => {
    const f = await fixture()
    const generator: CodeGeneratorPort = { generate: vi.fn(async (_spec, _plan, diagnostic) => { throw new Error(diagnostic === undefined ? 'JSON inválido' : diagnostic) }) }
    const result = await f.pipeline.run(actor, 'project', generator)
    expect(result).toMatchObject({ state: 'BUILD_FAILED', attempts: 3, message: 'JSON inválido' })
    expect(generator.generate).toHaveBeenNthCalledWith(2, spec, plan, 'JSON inválido')
    expect(f.execute).not.toHaveBeenCalled()
    const failures = f.runs.filter(run => run.state === 'FAILED')
    expect(failures).toHaveLength(3)
    expect(failures.every(run => run.stage === 'generate' && run.failure_code === 'JSON inválido')).toBe(true)
    expect(f.transitions).toEqual(['GENERATING', 'BUILD_FAILED'])
  })

  it('rejects forbidden imports before writing or running builder commands', async () => {
    const f = await fixture()
    const generator = { generate: vi.fn(async () => ({
      ...cleanGeneration,
      files: [{ path: 'src/GeneratedApp.tsx', content: "import { readFile } from 'node:fs'; export default function App(){ return null }; void readFile" }],
    })) }
    const result = await f.pipeline.run(actor, 'project', generator)
    expect(result).toMatchObject({ state: 'BUILD_FAILED', attempts: 3 })
    expect(result.message).toContain('node:fs')
    expect(f.execute).not.toHaveBeenCalled()
    expect(f.runs.filter(run => run.state === 'FAILED')).toHaveLength(3)
  })

  it('rejects a real personal identifier embedded in the AppSpec before preflight or generation', async () => {
    const f = await fixture()
    const unsafeSpec: AppSpecV1 = {
      ...spec,
      entities: [{ name: 'Cadastro', kind: 'database', sensitive: false, fields: [
        { name: 'Tipo', type: 'selection', required: true, options: ['CPF 529.982.247-25'] },
      ] }],
    }
    f.service.project.mockImplementation(() => ({ state: 'PLAN_APPROVED', category: 'form-database' }))
    f.service.latestSpec.mockReturnValue({ app_spec: unsafeSpec })
    const generator = { generate: vi.fn(async () => cleanGeneration) }
    await expect(f.pipeline.run(actor, 'project', generator)).rejects.toMatchObject({ code: 'INVALID' })
    expect(f.builder.preflight).not.toHaveBeenCalled()
    expect(generator.generate).not.toHaveBeenCalled()
    expect(f.runs).toHaveLength(0)
  })

  it('blocks before generation when the isolated builder is unavailable', async () => {
    const f = await fixture({ preflight: 'BLOCKED_EXTERNAL' }); const generator = { generate: vi.fn(async () => cleanGeneration) }
    await expect(f.pipeline.run(actor, 'project', generator)).resolves.toEqual({ state: 'BLOCKED_EXTERNAL', attempts: 0, message: 'Construtor indisponível.' })
    expect(generator.generate).not.toHaveBeenCalled()
    expect(f.transitions).toEqual([])
    expect(f.runs.at(-1)).toMatchObject({ stage: 'build', state: 'BLOCKED_EXTERNAL', sandbox: 'unavailable', artifact_sha256: null, failure_code: 'BUILDER_UNAVAILABLE' })
  })

  it('refuses to start without the approved plan and approved project state', async () => {
    const f = await fixture()
    f.service.plan.mockReturnValueOnce({ ...plan, status: 'PROPOSED' })
    await expect(f.pipeline.run(actor, 'project', { generate: vi.fn() })).rejects.toBeInstanceOf(PromptToAppError)
    expect(f.builder.preflight).not.toHaveBeenCalled()
  })

  it('records cancellation against the owning browser session before the next builder step', async () => {
    const controller = new AbortController()
    const f = await fixture({ execute: async () => { controller.abort('cancelled-by-user'); return { exitCode: 0, stdout: '', stderr: '', timedOut: false } } })
    const result = await f.pipeline.run({ ...actor, sessionId: 'browser-session' }, 'project', { generate: vi.fn(async () => cleanGeneration) }, { operationId: 'operation', ownerSessionId: 'browser-session', signal: controller.signal })
    expect(result).toMatchObject({ state: 'CANCELLED', attempts: 1 })
    expect(f.runs.at(-1)).toMatchObject({ run_id: 'operation', operation_id: 'operation', owner_session_id: 'browser-session', state: 'CANCELLED', artifact_sha256: null })
    expect(f.transitions).toEqual(['GENERATING', 'CANCELLED'])
  })
})

async function passAcceptance(directory: string): Promise<void> {
  const reportPath = resolve(directory, 'evidence/appspec-report.json')
  const report = JSON.parse(await readFile(reportPath, 'utf8')) as { checks: Array<{ status: string }> }
  report.checks = report.checks.map(check => check.status === 'PENDING' ? { ...check, status: 'PASSED' } : check)
  await writeFile(reportPath, JSON.stringify(report))
}

async function writeRuntimeOutput(directory: string): Promise<void> {
  await mkdir(resolve(directory, '.next/standalone'), { recursive: true })
  await mkdir(resolve(directory, '.next/static'), { recursive: true })
  await mkdir(resolve(directory, 'public'), { recursive: true })
  await writeFile(resolve(directory, '.next/standalone/server.js'), 'server')
  await writeFile(resolve(directory, '.next/static/app.js'), 'static')
  await writeFile(resolve(directory, 'public/logo.txt'), 'public')
}
