import { lstat, mkdtemp, mkdir, readFile, rm, symlink, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { afterEach, describe, expect, it, vi } from 'vitest'
import type { AppSpecV1 } from '../src/appspec.js'
import { createDesignSpec } from '../src/design.js'
import type { StudioPlan, StudioRun } from '../src/model.js'
import { PromptToAppPipeline, type CodeGeneratorPort } from '../src/pipeline.js'
import { BuilderLifecycleError, type BuildStep, type BuilderLifecycleFinished, type BuilderLifecycleResolverPort, type BuilderLifecycleSession, type BuilderLifecycleStepResult } from '../src/builder-lifecycle.js'
import { PromptToAppError, type PromptToAppActor, type PromptToAppService } from '../src/service.js'
import { latestGreenCheckpoint, runCheckpoints } from '../src/checkpoint.js'

const actor: PromptToAppActor = { userId: 'owner', orgId: 'org-a', tenantId: 'tenant-a', role: 'owner' }
const spec: AppSpecV1 = {
  schema_version: 1, problem: 'Apresentar serviços.', audience: 'Clientes', journeys: ['Conhecer serviços'],
  pages: [{ name: 'Início', sections: ['Serviços'] }], entities: [], sensitive_data: { detected: [], confirmed_by_user: false },
  accessibility: { wcag_level: 'AA', keyboard_required: true, reduced_motion: true }, language: 'pt-BR',
  acceptance_criteria: ['A página tem um título.'],
}
const plan: StudioPlan = {
  plan_id: 'plan', spec_id: 'spec', project_id: 'project', org_id: actor.orgId, tenant_id: actor.tenantId,
  slices: [{ slice_id: 'slice', title: 'Página', description: 'Criar página', acceptance_criteria: ['Compila'], planned_files: ['content/app.json', 'src/GeneratedApp.tsx'] }],
  status: 'APPROVED', created_at: '2026-09-03T12:00:00.000Z', updated_at: '2026-09-03T12:00:00.000Z',
}
const cleanGeneration = {
  files: [
    { path: 'content/app.json', content: '{"title":"Aurora","description":"Serviços"}' },
    { path: 'src/GeneratedApp.tsx', content: 'export default function GeneratedApp(){ return <main><h1>Início</h1><h2>Serviços</h2></main> }' },
  ], route: 'ollama', model: 'qwen', inputTokens: 10, outputTokens: 20,
} as const
const roots: string[] = []
afterEach(async () => Promise.all(roots.splice(0).map(root => rm(root, { recursive: true, force: true }))))

interface FixtureExecutionResult { readonly exitCode: number; readonly stdout: string; readonly stderr: string; readonly timedOut: boolean; readonly outputLimitExceeded?: boolean }
interface FixtureOptions {
  readonly preflight?: 'OK' | 'BLOCKED_EXTERNAL'
  readonly execute?: (directory: string, command: string) => Promise<FixtureExecutionResult>
  readonly finish?: BuilderLifecycleSession['finish']
  readonly emergencyStop?: { assertRunning(scope: { readonly orgId: string; readonly tenantId: string }): void }
  readonly generationTokenBudget?: number
}

async function fixture(options: FixtureOptions = {}) {
  const root = await mkdtemp(join(tmpdir(), 'dz23-pipeline-test-')); roots.push(root)
  const templateDirectory = resolve(root, 'template'); const runsRoot = resolve(root, 'runs')
  await mkdir(resolve(templateDirectory, 'src'), { recursive: true })
  await writeFile(resolve(templateDirectory, 'package.json'), '{"private":true}')
  await writeFile(resolve(templateDirectory, 'src/App.tsx'), 'export default function App(){ return null }')
  await writeFile(resolve(templateDirectory, 'next-env.d.ts'), '/// generated by Next.js')
  let state = 'PLAN_APPROVED'
  const runs: StudioRun[] = []; const transitions: string[] = []; const evidence: { kind: string; relative_path: string }[] = []
  const service = {
    project: vi.fn(() => ({ state, category: 'landing-page' })), plan: vi.fn(() => plan), latestSpec: vi.fn(() => ({ app_spec: spec })),
    designOrDefault: vi.fn(() => createDesignSpec({ preset: 'modern' })),
    transition: vi.fn(async (_actor, _projectId, to: string) => { state = to; transitions.push(to); return { state } }),
    putRun: vi.fn(async (_actor, run: StudioRun) => { runs.push(run) }),
    // `runs` existe aqui porque a RETOMADA precisa achar a execução anterior:
    // sem esta leitura, `findResumable` não tem onde procurar o diretório da
    // tentativa cancelada.
    runs: vi.fn(() => runs),
    putEvidence: vi.fn(async (_actor, item: { kind: string; relative_path: string }) => { evidence.push(item) }),
  }
  const executeImplementation: NonNullable<FixtureOptions['execute']> = options.execute ?? (async (): Promise<FixtureExecutionResult> => ({ exitCode: 0, stdout: 'ok', stderr: '', timedOut: false }))
  const execute = vi.fn(executeImplementation)
  let preparedDirectory = ''; let buildState: 'PREPARED' | 'INSTALL_OK' | 'BUILD_OK' | 'TEST_OK' | 'E2E_OK' | 'FAILED' | 'CANCELLED' = 'PREPARED'
  const builder: BuilderLifecycleSession = {
    preflight: vi.fn(async () => options.preflight === 'BLOCKED_EXTERNAL'
      ? { state: 'BLOCKED_EXTERNAL' as const }
      : { state: 'OK' as const }),
    prepare: vi.fn(async directory => { preparedDirectory = directory; buildState = 'PREPARED'; return { buildRef: 'build_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' } }),
    execute: vi.fn(async (_buildRef: string, step: BuildStep) => {
      const command = ({ install: 'pnpm install --offline', build: 'pnpm run build', test: 'pnpm run test', e2e: 'pnpm run test:e2e' } as const)[step]
      const result = await execute(preparedDirectory, command)
      buildState = result.exitCode === 0 ? ({ install: 'INSTALL_OK', build: 'BUILD_OK', test: 'TEST_OK', e2e: 'E2E_OK' } as const)[step] : 'FAILED'
      return { state: buildState, step, result: { exit_code: result.exitCode, stdout: result.stdout, stderr: result.stderr, timed_out: result.timedOut, termination_reason: result.outputLimitExceeded === true ? 'output_limit' as const : result.timedOut ? 'timeout' as const : null, output_limit_exceeded: result.outputLimitExceeded === true } }
    }),
    cancel: vi.fn(async () => { buildState = 'CANCELLED' }),
    finish: vi.fn(options.finish ?? (async () => ({ finalState: buildState === 'E2E_OK' ? 'E2E_OK' as const : buildState === 'CANCELLED' ? 'CANCELLED' as const : 'FAILED' as const, exported: buildState === 'E2E_OK' ? { relative_path: 'exports/build_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', sha256: 'a'.repeat(64), files: 1, bytes: 1 } : null, cleanupPending: false, cleaned: true }))),
    listManaged: vi.fn(async () => []),
  }
  const resolver: BuilderLifecycleResolverPort<PromptToAppActor> = { forActor: vi.fn(async () => builder) }
  let id = 0
  const pipeline = new PromptToAppPipeline({
    service: service as unknown as PromptToAppService, builder: resolver,
    templateDirectory, runsRoot, now: () => new Date('2026-09-03T12:00:00.000Z'), createId: () => `id-${++id}`,
    ...(options.emergencyStop === undefined ? {} : { emergencyStop: options.emergencyStop }),
    ...(options.generationTokenBudget === undefined ? {} : { generationTokenBudget: options.generationTokenBudget }),
  })
  return { pipeline, service, builder, resolver, execute, runs, transitions, evidence, templateDirectory, runsRoot }
}

describe('Prompt-to-App pipeline', () => {
  it('T-08: a MESMA falha repetida muda o pedido — a terceira tentativa nao pede igual a segunda', async () => {
    // O laco tenta tres vezes e passa ao gerador o diagnostico da vez
    // anterior. Falhando sempre pelo mesmo motivo, a terceira pedia
    // exatamente a mesma correcao da segunda: mesma falha, mesma estrategia.
    const f = await fixture({ execute: async () => ({ exitCode: 1, stdout: '', stderr: 'sempre a mesma falha', timedOut: false }) })
    const generator: CodeGeneratorPort = { generate: vi.fn(async () => cleanGeneration) }
    await f.pipeline.run(actor, 'project', generator)

    expect(generator.generate).toHaveBeenCalledTimes(3)
    const pedidos = vi.mocked(generator.generate).mock.calls.map(call => call[2])
    // A primeira nao tem correcao nenhuma: nada falhou ainda.
    expect(pedidos[0]).toBeUndefined()
    // A segunda leva o diagnostico cru da primeira.
    expect(pedidos[1]).toBeDefined()
    expect(pedidos[1]).not.toContain('Mude de estratégia')
    // A TERCEIRA leva o aviso: aquela correcao ja foi pedida e deu no mesmo.
    expect(pedidos[2]).toContain('Mude de estratégia')
    // E o diagnostico original continua la: mudar de abordagem nao e esquecer
    // qual era o problema.
    expect(pedidos[2]).toContain(pedidos[1]!)
  })

  it.skipIf(process.platform === 'win32')('rejects a template symlink before creating a run or changing project state', async () => {
    const f = await fixture(); const outside = await mkdtemp(join(tmpdir(), 'dz23-template-outside-')); roots.push(outside)
    await symlink(outside, resolve(f.templateDirectory, 'linked'), 'dir')
    const generator = { generate: vi.fn(async () => cleanGeneration) }
    await expect(f.pipeline.run(actor, 'project', generator)).rejects.toThrow('Link simbólico')
    expect(generator.generate).not.toHaveBeenCalled()
    expect(f.runs).toEqual([])
    expect(f.transitions).toEqual([])
  })

  /**
   * O ciclo do construtor relatando o que os testes do app gerado acharam.
   *
   * O relatório de aceitação é escrito pelo pipeline com todos os critérios
   * `PENDING`; quem os resolve é a suíte do próprio app, no passo `test`. Este
   * duplo faz exatamente isso - e nada além disso.
   */
  const reportingExecute = (statuses: 'PASSED' | 'FAILED') => async (directory: string, command: string) => {
    if (command === 'pnpm run test') {
      const path = resolve(directory, 'evidence', 'appspec-report.json')
      const report = JSON.parse(await readFile(path, 'utf8')) as { checks: { status: string }[] }
      for (const check of report.checks) if (check.status === 'PENDING') check.status = statuses
      await writeFile(path, JSON.stringify(report), 'utf8')
    }
    return { exitCode: 0, stdout: 'ok', stderr: '', timedOut: false }
  }

  const attestingFinish: BuilderLifecycleSession['finish'] = async (): Promise<BuilderLifecycleFinished> => ({
    finalState: 'E2E_OK',
    exported: { relative_path: 'exports/build_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', sha256: 'a'.repeat(64), files: 1, bytes: 1 },
    cleanupPending: false, cleaned: true,
    attestation: { image_digest: `sha256:${'d'.repeat(64)}`, policy_sha256: 'f'.repeat(64), scope_id: 's_1' },
  })

  it('conclui a jornada quando o construtor declara imagem e política, gravando as quatro atestações', async () => {
    // O caminho de SUCESSO estava morto: um ciclo que passava lançava
    // ACCEPTANCE_ATTESTATION_UNAVAILABLE e levava embora VERIFIED_PROTOTYPE, a
    // prévia e o aviso à pessoa. Este é o teste que prova que ele voltou.
    const f = await fixture({ execute: reportingExecute('PASSED'), finish: attestingFinish })
    const result = await f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })
    expect(result).toMatchObject({ state: 'VERIFIED_PROTOTYPE', attempts: 1 })
    expect(f.transitions).toEqual(['GENERATING', 'BUILD_OK', 'TESTS_OK', 'VERIFIED_PROTOTYPE'])
    const run = f.runs.at(-1)!
    expect(run).toMatchObject({ state: 'PASSED', stage: 'verify', artifact_sha256: 'a'.repeat(64), template_integrity: 'VERIFIED' })
    // Os RESUMOS ficam no registro; os documentos inteiros vivem em evidence/.
    // Um manifesto completo dentro da chave-valor cresceria sem teto.
    expect(run.attestations).toEqual({
      acceptance_sha256: expect.stringMatching(/^[a-f0-9]{64}$/u),
      manifest_sha256: expect.stringMatching(/^[a-f0-9]{64}$/u),
      sbom_sha256: expect.stringMatching(/^[a-f0-9]{64}$/u),
      provenance_sha256: expect.stringMatching(/^[a-f0-9]{64}$/u),
      builder_image_digest: `sha256:${'d'.repeat(64)}`,
      policy_sha256: 'f'.repeat(64),
    })
    const written = f.evidence.map(item => item.relative_path)
    for (const name of ['acceptance', 'manifest', 'sbom', 'provenance']) {
      expect(written.some(path => path.endsWith(`evidence/attestation-${name}.json`)), name).toBe(true)
    }
    // A atestação de aceitação diz APROVADO e mostra em quê se baseou.
    const directory = run.run_directory
    const acceptance = JSON.parse(await readFile(resolve(directory, 'evidence/attestation-acceptance.json'), 'utf8')) as Record<string, unknown>
    expect(acceptance).toMatchObject({
      kind: 'dz23.acceptance', verdict: 'PASSED', template_integrity: 'VERIFIED',
      builder: { image_digest: `sha256:${'d'.repeat(64)}`, policy_sha256: 'f'.repeat(64), scope_id: 's_1' },
    })
    expect((acceptance.summary as { failed: number, pending: number })).toMatchObject({ failed: 0, pending: 0 })
    // A proveniência não se cala sobre o que ela NÃO prova.
    const provenance = JSON.parse(await readFile(resolve(directory, 'evidence/attestation-provenance.json'), 'utf8')) as Record<string, unknown>
    expect(provenance).toMatchObject({ signed: false, manifest_sha256: run.attestations!.manifest_sha256 })
    // O SBOM lista o que o app declara - aqui, um package.json sem dependência
    // nenhuma, que é "declarado com zero" e não "indisponível".
    const sbom = JSON.parse(await readFile(resolve(directory, 'evidence/attestation-sbom.json'), 'utf8')) as Record<string, unknown>
    expect(sbom).toMatchObject({ source: 'declared', unavailable_reason: null, components: [] })
  })

  it('grava cada passo do construtor ENQUANTO ele acontece, e não só no fim', async () => {
    // "A ideia desse projeto é ver a construção em tempo real." A tela mostrava
    // uma frase por ETAPA - `build` ou `test` -, e o construtor roda quatro
    // passos dentro dessas duas. Durante os minutos mais longos do produto a
    // pessoa via um texto imóvel enquanto quatro coisas diferentes aconteciam,
    // e "trabalhando" e "travado" tinham a mesma aparência.
    //
    // O que este teste afirma é o TEMPO REAL, não o resultado: existe um
    // registro em que `install` já terminou e `build` está em andamento. Um
    // registro que só ganhasse os passos no fim passaria por um teste que
    // olhasse apenas `runs.at(-1)` - e não mostraria nada a ninguém enquanto a
    // espera acontece, que é o defeito inteiro.
    const f = await fixture({ execute: reportingExecute('PASSED'), finish: attestingFinish })
    await f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })

    const live = f.runs.find(run => run.steps?.some(entry => entry.state === 'RUNNING'))
    expect(live, 'nenhum registro pegou um passo em andamento').toBeDefined()

    const midway = f.runs.find(run =>
      run.steps?.[0]?.step === 'install' && run.steps[0].state === 'PASSED'
      && run.steps[1]?.step === 'build' && run.steps[1].state === 'RUNNING')
    expect(midway, 'nenhum registro mostra install pronto com build em andamento').toBeDefined()
    // O passo em andamento não tem fim: inventar um seria mostrar duração para
    // algo que ainda está acontecendo.
    expect(midway!.steps![1]!.finished_at).toBeNull()
    expect(midway!.steps![0]!.finished_at).not.toBeNull()

    // No fim, os quatro passos estão lá, na ordem do construtor, todos fechados.
    const final = f.runs.at(-1)!
    expect(final.steps?.map(entry => entry.step)).toEqual(['install', 'build', 'test', 'e2e'])
    expect(final.steps?.every(entry => entry.state === 'PASSED')).toBe(true)
    expect(final.steps?.every(entry => entry.finished_at !== null)).toBe(true)
  })

  it('um passo que reprova é gravado como reprovado, e os seguintes não aparecem', async () => {
    // Um passo eternamente RUNNING faria a tela girar para sempre num passo que
    // já acabou - a aparência exata de um travamento. E um passo que nunca
    // rodou NÃO pode aparecer: ausência aqui quer dizer "não chegou a
    // acontecer", nunca "pulado com sucesso".
    const f = await fixture({
      execute: async (_directory: string, command: string) => command.includes('build')
        ? { exitCode: 1, stdout: '', stderr: 'erro de compilação', timedOut: false }
        : { exitCode: 0, stdout: 'ok', stderr: '', timedOut: false },
    })
    await f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })
    const withSteps = f.runs.filter(run => run.steps !== undefined && run.steps.length > 0)
    expect(withSteps.length).toBeGreaterThan(0)
    const last = withSteps.at(-1)!
    expect(last.steps!.map(entry => [entry.step, entry.state])).toEqual([['install', 'PASSED'], ['build', 'FAILED']])
    expect(last.steps!.every(entry => entry.state !== 'RUNNING')).toBe(true)
  })

  it('uma criação cancelada RETOMA de onde parou, sem chamar o modelo de novo', async () => {
    // Cancelar recomeçava do ZERO. Quem apertava "Cancelar" depois de esperar
    // — porque precisava do computador, porque fechou o navegador — perdia a
    // geração inteira e pagava o modelo outra vez.
    //
    // E o custo é o MENOR dos dois problemas. Geração não é determinística:
    // pedir de novo, com o mesmo plano, devolve um aplicativo DIFERENTE. A
    // pessoa aprovava um plano, esperava, cancelava, mandava recomeçar — e
    // recebia outra coisa. Retomar é o que faz a segunda tentativa entregar o
    // que a primeira estava construindo.
    const controller = new AbortController()
    const f = await fixture({
      // O cancelamento acontece DEPOIS da geração e DENTRO da construção, que
      // é exatamente a janela em que havia trabalho para perder.
      execute: async (_directory: string, command: string) => {
        if (command.includes('run build')) controller.abort()
        return { exitCode: 0, stdout: 'ok', stderr: '', timedOut: false }
      },
    })
    const generator = { generate: vi.fn(async () => cleanGeneration) }
    const cancelled = await f.pipeline.run(actor, 'project', generator, { signal: controller.signal })
    expect(cancelled).toMatchObject({ state: 'CANCELLED' })
    expect(generator.generate).toHaveBeenCalledTimes(1)
    const cancelledRun = f.runs.at(-1)!
    expect(cancelledRun.state).toBe('CANCELLED')

    // O marco de geração ficou em disco: é ele que torna a retomada um FATO
    // verificável, e não uma suposição sobre o que sobrou na pasta.
    const marker = JSON.parse(await readFile(resolve(cancelledRun.run_directory, 'generation.json'), 'utf8')) as Record<string, unknown>
    expect(marker).toMatchObject({ plan_id: plan.plan_id, attempt: 1, route: 'ollama', model: 'qwen' })

    // Segunda execução, sem sinal de cancelamento: retoma.
    const second = await fixture({ execute: reportingExecute('PASSED'), finish: attestingFinish })
    // A mesma pasta e a mesma memória de execuções da primeira.
    second.runs.push(...f.runs)
    const resumedGenerator = { generate: vi.fn(async () => cleanGeneration) }
    await second.service.transition(actor, 'project', 'CANCELLED')
    second.runs.length = 0
    second.runs.push(cancelledRun)
    const result = await second.pipeline.run(actor, 'project', resumedGenerator)

    // O MODELO NÃO FOI CHAMADO. Esta é a afirmação inteira.
    expect(resumedGenerator.generate).not.toHaveBeenCalled()
    expect(result.state).toBe('VERIFIED_PROTOTYPE')
    // E a retomada não é invisível: o registro diz de onde veio, senão ninguém
    // conseguiria auditar depois qual geração produziu o artefato.
    expect(second.runs.at(-1)?.resumed_from_run_id).toBe(cancelledRun.run_id)
  })

  it('NÃO retoma quando o plano mudou depois do cancelamento', async () => {
    // Os arquivos guardados respondem à pergunta ANTIGA. Reaproveitá-los depois
    // que a pessoa mudou o plano entregaria calado o aplicativo que ela acabou
    // de deixar de querer — que é pior do que gerar de novo.
    const controller = new AbortController()
    const f = await fixture({
      execute: async (_directory: string, command: string) => {
        if (command.includes('run build')) controller.abort()
        return { exitCode: 0, stdout: 'ok', stderr: '', timedOut: false }
      },
    })
    await f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) }, { signal: controller.signal })
    const cancelledRun = f.runs.at(-1)!

    const second = await fixture({ execute: reportingExecute('PASSED'), finish: attestingFinish })
    second.runs.length = 0
    second.runs.push(cancelledRun)
    await second.service.transition(actor, 'project', 'CANCELLED')
    // O plano de agora é outro.
    second.service.plan.mockReturnValue({ ...plan, plan_id: 'plano-diferente' })
    const generator = { generate: vi.fn(async () => cleanGeneration) }
    await second.pipeline.run(actor, 'project', generator)
    expect(generator.generate).toHaveBeenCalledTimes(1)
    expect(second.runs.at(-1)?.resumed_from_run_id).toBeUndefined()
  })

  it('NÃO retoma uma execução que REPROVOU: repetir existe para corrigir', async () => {
    // "Tentar novamente" depois de uma reprovação precisa gerar de novo, com o
    // diagnóstico do que falhou. Reaproveitar a geração reprovada entregaria o
    // mesmo defeito com outro nome, e a pessoa apertaria o botão para sempre.
    const f = await fixture({
      execute: async (_directory: string, command: string) => command.includes('run build')
        ? { exitCode: 1, stdout: '', stderr: 'quebrou', timedOut: false }
        : { exitCode: 0, stdout: 'ok', stderr: '', timedOut: false },
    })
    const generator = { generate: vi.fn(async () => cleanGeneration) }
    const failed = await f.pipeline.run(actor, 'project', generator)
    expect(failed.state).toBe('BUILD_FAILED')
    // Três tentativas, três chamadas: o marco existe em disco e mesmo assim
    // NENHUMA delas retomou.
    expect(generator.generate).toHaveBeenCalledTimes(3)
    expect(f.runs.every(run => run.resumed_from_run_id === undefined)).toBe(true)
  })

  it('um critério REPROVADO derruba a atestação, e o ciclo verde do construtor não salva a execução', async () => {
    // O veredito da atestação é o que a pessoa vai mostrar a alguém: ele manda
    // sobre o "passou" do construtor.
    const f = await fixture({ execute: reportingExecute('FAILED'), finish: attestingFinish })
    const result = await f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })
    expect(result).toMatchObject({ state: 'TESTS_FAILED' })
    expect(f.runs.some(run => run.state === 'PASSED')).toBe(false)
    expect(f.runs.at(-1)).toMatchObject({ failure_code: 'ACCEPTANCE_ATTESTATION_FAILED' })
    expect(f.runs.at(-1)?.attestations).toBeUndefined()
    expect(f.transitions).not.toContain('VERIFIED_PROTOTYPE')
  })

  it('does not promote supervisor success while the authenticated exported acceptance report is unavailable', async () => {
    const f = await fixture(); const generator = { generate: vi.fn(async () => cleanGeneration) }
    const result = await f.pipeline.run(actor, 'project', generator)
    expect(result).toMatchObject({ state: 'BLOCKED_EXTERNAL', attempts: 1 })
    expect(f.transitions).toEqual(['GENERATING', 'INTERRUPTED'])
    expect(f.execute).toHaveBeenCalledTimes(4)
    expect(f.resolver.forActor).toHaveBeenCalledOnce()
    expect(f.runs.at(-1)).toMatchObject({ stage: 'verify', state: 'BLOCKED_EXTERNAL', failure_code: 'ACCEPTANCE_ATTESTATION_UNAVAILABLE', artifact_sha256: null })
    expect(f.runs.some(run => run.state === 'PASSED')).toBe(false)
    expect(f.runs.flatMap(run => run.acceptance_checks).some(check => check.status === 'PENDING')).toBe(true)
    expect(f.runs.at(-1)).toMatchObject({ operation_id: expect.any(String), owner_session_id: 'direct-execution' })
    // Uma execução bloqueada não promove nada, mas EXPLICA: o relato do que
    // aconteceu é a única evidência gravada, e é o que tira a pessoa de um
    // código em inglês. Nenhuma evidência de build ou artefato aparece aqui.
    expect(f.evidence.map(item => item.kind)).toEqual(['diff'])
    expect(f.evidence[0]?.relative_path).toMatch(/run-report\.json$/u)
  })

  it('rejects hostile operation identifiers before creating a run path', async () => {
    const f = await fixture(); const escaped = resolve(f.runsRoot, '..', 'escaped')
    await expect(f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) }, { operationId: '../escaped' })).rejects.toMatchObject({ code: 'INVALID' })
    await expect(lstat(escaped)).rejects.toMatchObject({ code: 'ENOENT' })
    expect(f.runs).toEqual([])
    expect(f.transitions).toEqual([])
  })

  it.each([
    ['missing checks', '{}'],
    ['invalid JSON', '{'],
    ['empty checks', '{"schema_version":1,"checks":[]}'],
  ])('fails closed when the AppSpec report has %s', async (_case, content) => {
    const f = await fixture({ execute: async (directory, command) => {
      if (command === 'pnpm run test:e2e') await writeFile(resolve(directory, 'evidence/appspec-report.json'), content)
      return { exitCode: 0, stdout: 'ok', stderr: '', timedOut: false }
    } })
    await expect(f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })).resolves.toMatchObject({ state: 'TESTS_FAILED' })
    expect(f.runs.some(run => run.state === 'PASSED')).toBe(false)
    expect(f.transitions).not.toContain('VERIFIED_PROTOTYPE')
    expect(f.runs.at(-1)).toMatchObject({ state: 'FAILED', failure_code: 'APPSPEC_REPORT_INVALID' })
  })

  it('never records PASS when finish cannot prove cleanup', async () => {
    const f = await fixture({ execute: async (directory, command) => {
      if (command === 'pnpm run test:e2e') await passAcceptance(directory)
      return { exitCode: 0, stdout: 'ok', stderr: '', timedOut: false }
    }, finish: async () => ({ finalState: 'E2E_OK', exported: { relative_path: 'exports/build_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', sha256: 'a'.repeat(64), files: 1, bytes: 1 }, cleanupPending: true, cleaned: false }) })
    await expect(f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })).resolves.toMatchObject({ state: 'BLOCKED_EXTERNAL', attempts: 1 })
    expect(f.runs.at(-1)).toMatchObject({ state: 'BLOCKED_EXTERNAL', failure_code: 'FINISH_INCONCLUSIVE', artifact_sha256: null })
    expect(f.transitions).toEqual(['GENERATING', 'INTERRUPTED'])
    expect(f.service.project()).toMatchObject({ state: 'INTERRUPTED' })
  })

  it('terminalizes an unexpected test-process failure without leaving GENERATING', async () => {
    const f = await fixture({ execute: async (directory, command) => {
      if (command === 'pnpm run build') await writeRuntimeOutput(directory)
      if (command === 'pnpm run test') throw new Error('subprocess-channel-lost')
      return { exitCode: 0, stdout: 'ok', stderr: '', timedOut: false }
    } })
    await expect(f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })).resolves.toMatchObject({ state: 'TESTS_FAILED' })
    expect(f.runs.at(-1)).toMatchObject({ state: 'FAILED', stage: 'test', failure_code: 'PIPELINE_UNEXPECTED_FAILURE' })
    expect(f.transitions).toEqual(['GENERATING', 'BUILD_OK', 'TESTS_FAILED'])
  })

  it('records an inconclusive lifecycle channel as interrupted instead of a logical build failure', async () => {
    const f = await fixture()
    f.builder.execute = vi.fn(async () => { throw new BuilderLifecycleError('INTERRUPTED', 'INVALID_STEP_ORDER') })
    const result = await f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })
    expect(result).toMatchObject({ state: 'INTERRUPTED', attempts: 1 })
    expect(f.runs.at(-1)).toMatchObject({ state: 'FAILED', failure_code: 'INVALID_STEP_ORDER', artifact_sha256: null })
    expect(f.transitions).toEqual(['GENERATING', 'INTERRUPTED'])
  })

  it('does not trust a locally forged PASSED report as exported evidence', async () => {
    const f = await fixture()
    const execute: BuilderLifecycleSession['execute'] = async (_buildRef: string, step: BuildStep): Promise<BuilderLifecycleStepResult> => {
      if (step === 'e2e') await passAcceptance(resolve(f.runsRoot, 'id-1'))
      return { state: ({ install: 'INSTALL_OK', build: 'BUILD_OK', test: 'TEST_OK', e2e: 'E2E_OK' } as const)[step], step, result: { exit_code: 0, stdout: '', stderr: '', timed_out: false, termination_reason: null, output_limit_exceeded: false } }
    }
    const finish: BuilderLifecycleSession['finish'] = async (): Promise<BuilderLifecycleFinished> => ({ finalState: 'E2E_OK', exported: { relative_path: 'exports/build_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', sha256: 'a'.repeat(64), files: 1, bytes: 1 }, cleanupPending: false, cleaned: true })
    f.builder.execute = vi.fn(execute)
    f.builder.finish = vi.fn(finish)
    await expect(f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })).resolves.toMatchObject({ state: 'BLOCKED_EXTERNAL' })
    expect(f.runs.at(-1)).toMatchObject({ state: 'BLOCKED_EXTERNAL', stage: 'verify', failure_code: 'ACCEPTANCE_ATTESTATION_UNAVAILABLE', artifact_sha256: null })
    expect(f.transitions).toEqual(['GENERATING', 'INTERRUPTED'])
    expect(f.transitions).not.toContain('VERIFIED_PROTOTYPE')
  })

  it('rejects an oversized acceptance report before parsing it', async () => {
    const f = await fixture({ execute: async (directory, command) => {
      if (command === 'pnpm run test:e2e') await writeFile(resolve(directory, 'evidence/appspec-report.json'), ' '.repeat(1024 * 1024 + 1))
      return { exitCode: 0, stdout: 'ok', stderr: '', timedOut: false }
    } })
    await expect(f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })).resolves.toMatchObject({ state: 'TESTS_FAILED' })
    expect(f.runs.at(-1)).toMatchObject({ state: 'FAILED', failure_code: 'APPSPEC_REPORT_TOO_LARGE' })
  })

  it('does not retry a process that exceeds the output budget', async () => {
    const f = await fixture({ execute: async () => ({
      exitCode: -1, stdout: 'bounded', stderr: '', timedOut: false,
      terminationReason: 'output_limit' as const, outputLimitExceeded: true,
    }) })
    await expect(f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })).resolves.toMatchObject({ state: 'BUILD_FAILED', attempts: 1 })
    expect(f.execute).toHaveBeenCalledTimes(1)
    expect(f.runs.at(-1)).toMatchObject({ state: 'FAILED', failure_code: 'PROCESS_OUTPUT_LIMIT_EXCEEDED' })
  })

  it('allows only the framework-generated next-env file to change during build', async () => {
    const f = await fixture({ execute: async (directory, command) => {
      if (command === 'pnpm run build') { await writeRuntimeOutput(directory); await writeFile(resolve(directory, 'next-env.d.ts'), '/// regenerated by Next.js') }
      if (command === 'pnpm run test:e2e') await passAcceptance(directory)
      return { exitCode: 0, stdout: 'ok', stderr: '', timedOut: false }
    } })
    await expect(f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })).resolves.toMatchObject({ state: 'BLOCKED_EXTERNAL' })
  })

  it('rejects a build that changes another protected template file', async () => {
    const f = await fixture({ execute: async (directory, command) => {
      if (command === 'pnpm run build') { await writeRuntimeOutput(directory); await writeFile(resolve(directory, 'src/App.tsx'), 'tampered') }
      if (command === 'pnpm run test:e2e') await passAcceptance(directory)
      return { exitCode: 0, stdout: 'ok', stderr: '', timedOut: false }
    } })
    await expect(f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })).resolves.toMatchObject({ state: 'BUILD_FAILED', message: 'TEMPLATE_INTEGRITY_FAILED' })
  })

  it('records the template integrity verdict on the attempt, and a tampered attempt is never a safe point', async () => {
    // O veredito era CALCULADO e jogado fora quando batia: sem gravá-lo, E-08
    // só saberia que a tentativa não reprovou, e não que ela foi conferida.
    const tampered = await fixture({ execute: async (directory, command) => {
      if (command === 'pnpm run build') { await writeRuntimeOutput(directory); await writeFile(resolve(directory, 'src/App.tsx'), 'tampered') }
      if (command === 'pnpm run test:e2e') await passAcceptance(directory)
      return { exitCode: 0, stdout: 'ok', stderr: '', timedOut: false }
    } })
    await tampered.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })
    const recusada = tampered.runs.filter(run => run.failure_code === 'TEMPLATE_INTEGRITY_FAILED')
    expect(recusada.length).toBeGreaterThan(0)
    expect(recusada.every(run => run.template_integrity === 'FAILED')).toBe(true)
    expect(runCheckpoints(recusada).every(checkpoint => !checkpoint.green)).toBe(true)
    expect(latestGreenCheckpoint(runCheckpoints(tampered.runs))).toBe(null)

    // E quando os passos rodam sem adulteração, a conferência que APROVOU fica
    // registrada — é ela que um ponto seguro exige quando a atestação existir.
    const clean = await fixture({ execute: async (directory, command) => {
      if (command === 'pnpm run test') return { exitCode: 1, stdout: '', stderr: 'falhou', timedOut: false }
      if (command === 'pnpm run build') await writeRuntimeOutput(directory)
      return { exitCode: 0, stdout: 'ok', stderr: '', timedOut: false }
    } })
    await clean.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })
    expect(clean.runs.some(run => run.template_integrity === 'VERIFIED')).toBe(true)
    // Integridade conferida NÃO é um verde: os passos não passaram.
    expect(latestGreenCheckpoint(runCheckpoints(clean.runs))).toBe(null)
  })

  it('distinguishes a test failure from a build failure after three attempts', async () => {
    const f = await fixture({ execute: async (_directory, command) => ({ exitCode: command === 'pnpm run test' ? 1 : 0, stdout: '', stderr: '', timedOut: false }) })
    const result = await f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })
    expect(result).toMatchObject({ state: 'TESTS_FAILED', attempts: 3 })
    expect(f.transitions).toEqual(['GENERATING', 'BUILD_OK', 'TESTS_FAILED'])
    const failures = f.runs.filter(run => run.state === 'FAILED')
    expect(failures).toHaveLength(3)
    expect(failures.every(run => run.stage === 'test' && run.failure_code === 'test: exit 1')).toBe(true)
    expect(failures.every(run => run.artifact_sha256 == null)).toBe(true)
  })

  it('retries rejected model output with the prior diagnostic and closes as build failed', async () => {
    const f = await fixture()
    const generator: CodeGeneratorPort = { generate: vi.fn(async (_spec, _plan, diagnostic) => { throw new Error(diagnostic === undefined ? 'JSON inválido' : diagnostic) }) }
    const result = await f.pipeline.run(actor, 'project', generator)
    expect(result).toMatchObject({ state: 'BUILD_FAILED', attempts: 3, message: 'JSON inválido' })
    expect(generator.generate).toHaveBeenNthCalledWith(2, spec, plan, 'JSON inválido')
    expect(f.execute).not.toHaveBeenCalled()
    const failures = f.runs.filter(run => run.state === 'FAILED')
    expect(failures).toHaveLength(3)
    expect(failures.every(run => run.stage === 'generate' && run.failure_code === 'JSON inválido')).toBe(true)
    expect(f.transitions).toEqual(['GENERATING', 'BUILD_FAILED'])
  })

  /**
   * O teto de tokens de UMA criação, somando as três tentativas.
   *
   * Até aqui o único teto era de TEMPO, por passo do construtor — e tempo não é
   * o que a pessoa paga. Numa instalação com chave própria, três tentativas
   * sobre uma especificação grande gastavam o que gastassem.
   */
  it('para a criação quando o teto de tokens acaba, e diz que foi orçamento', async () => {
    const f = await fixture({ generationTokenBudget: 1_000 })
    // A cobrança acontece na geração BEM-SUCEDIDA: esta entrega os arquivos
    // (por isso cobra) e é recusada depois, na verificação de importação, para
    // forçar a repetição — que é onde o gasto multiplica.
    const spending: CodeGeneratorPort = {
      generate: vi.fn(async () => ({
        ...cleanGeneration,
        files: [{ path: 'src/GeneratedApp.tsx', content: "import { readFile } from 'node:fs'; export default function App(){ return null }; void readFile" }],
        inputTokens: 400, outputTokens: 200,
      })),
    }
    const result = await f.pipeline.run(actor, 'project', spending)

    // 600 na primeira tentativa, 1200 na segunda: a TERCEIRA não começa.
    expect(spending.generate).toHaveBeenCalledTimes(2)
    expect(result.state).toBe('BUDGET_EXCEEDED')
    const stopped = f.runs.at(-1)!
    expect(stopped.state).toBe('BUDGET_EXCEEDED')
    expect(stopped.failure_code).toContain('GENERATION_TOKEN_BUDGET_EXCEEDED')
    // O gasto somado viaja no diagnóstico: sem ele, quem opera não sabe se o
    // teto era apertado demais ou se a especificação é que é cara.
    expect(stopped.failure_code).toContain('tokens=1200')
  })

  it('sem teto configurado, a criação usa as três tentativas', async () => {
    // O padrão NÃO é um limite inventado por mim: sem configuração, não há teto.
    const f = await fixture()
    const spending: CodeGeneratorPort = {
      generate: vi.fn(async () => ({
        ...cleanGeneration,
        files: [{ path: 'src/GeneratedApp.tsx', content: "import { readFile } from 'node:fs'; export default function App(){ return null }; void readFile" }],
        inputTokens: 400_000, outputTokens: 200_000,
      })),
    }
    const result = await f.pipeline.run(actor, 'project', spending)
    expect(spending.generate).toHaveBeenCalledTimes(3)
    expect(result.state).toBe('BUILD_FAILED')
  })

  it('rejects forbidden imports before writing or running builder commands', async () => {
    const f = await fixture()
    const generator = { generate: vi.fn(async () => ({
      ...cleanGeneration,
      files: [{ path: 'src/GeneratedApp.tsx', content: "import { readFile } from 'node:fs'; export default function App(){ return null }; void readFile" }],
    })) }
    const result = await f.pipeline.run(actor, 'project', generator)
    expect(result).toMatchObject({ state: 'BUILD_FAILED', attempts: 3 })
    expect(result.message).toContain('node:fs')
    expect(f.execute).not.toHaveBeenCalled()
    expect(f.runs.filter(run => run.state === 'FAILED')).toHaveLength(3)
  })

  it('rejects a real personal identifier embedded in the AppSpec before preflight or generation', async () => {
    const f = await fixture()
    const unsafeSpec: AppSpecV1 = {
      ...spec,
      entities: [{ name: 'Cadastro', kind: 'database', sensitive: false, fields: [
        { name: 'Tipo', type: 'selection', required: true, options: ['CPF 529.982.247-25'] },
      ] }],
    }
    f.service.project.mockImplementation(() => ({ state: 'PLAN_APPROVED', category: 'form-database' }))
    f.service.latestSpec.mockReturnValue({ app_spec: unsafeSpec })
    const generator = { generate: vi.fn(async () => cleanGeneration) }
    await expect(f.pipeline.run(actor, 'project', generator)).rejects.toMatchObject({ code: 'INVALID' })
    expect(f.builder.preflight).not.toHaveBeenCalled()
    expect(generator.generate).not.toHaveBeenCalled()
    expect(f.runs).toHaveLength(0)
  })

  it('blocks before generation when the isolated builder is unavailable', async () => {
    const f = await fixture({ preflight: 'BLOCKED_EXTERNAL' }); const generator = { generate: vi.fn(async () => cleanGeneration) }
    await expect(f.pipeline.run(actor, 'project', generator)).resolves.toEqual({ state: 'BLOCKED_EXTERNAL', attempts: 0, message: 'O ambiente isolado para criar seu projeto não está disponível neste computador.' })
    expect(generator.generate).not.toHaveBeenCalled()
    expect(f.transitions).toEqual([])
    expect(f.runs.at(-1)).toMatchObject({ stage: 'build', state: 'BLOCKED_EXTERNAL', sandbox: 'unavailable', artifact_sha256: null, failure_code: 'BUILDER_UNAVAILABLE' })
    await expect(lstat(f.runsRoot)).rejects.toMatchObject({ code: 'ENOENT' })
  })

  it('refuses to start without the approved plan and approved project state', async () => {
    const f = await fixture()
    f.service.plan.mockReturnValueOnce({ ...plan, status: 'PROPOSED' })
    await expect(f.pipeline.run(actor, 'project', { generate: vi.fn() })).rejects.toBeInstanceOf(PromptToAppError)
    expect(f.builder.preflight).not.toHaveBeenCalled()
  })

  it('records cancellation against the owning browser session before the next builder step', async () => {
    const controller = new AbortController()
    const f = await fixture({ execute: async () => { controller.abort('cancelled-by-user'); return { exitCode: 0, stdout: '', stderr: '', timedOut: false } } })
    const result = await f.pipeline.run({ ...actor, sessionId: 'browser-session' }, 'project', { generate: vi.fn(async () => cleanGeneration) }, { operationId: 'operation', ownerSessionId: 'browser-session', signal: controller.signal })
    expect(result).toMatchObject({ state: 'CANCELLED', attempts: 1 })
    expect(f.runs.at(-1)).toMatchObject({ run_id: 'operation', operation_id: 'operation', owner_session_id: 'browser-session', state: 'CANCELLED', artifact_sha256: null })
    expect(f.transitions).toEqual(['GENERATING', 'CANCELLED'])
    expect(f.builder.cancel).toHaveBeenCalledOnce()
    expect(f.builder.finish).toHaveBeenCalledOnce()
  })
})

async function passAcceptance(directory: string): Promise<void> {
  const reportPath = resolve(directory, 'evidence/appspec-report.json')
  const report = JSON.parse(await readFile(reportPath, 'utf8')) as { checks: Array<{ status: string }> }
  report.checks = report.checks.map(check => check.status === 'PENDING' ? { ...check, status: 'PASSED' } : check)
  await writeFile(reportPath, JSON.stringify(report))
}

async function writeRuntimeOutput(directory: string): Promise<void> {
  await mkdir(resolve(directory, '.next/standalone'), { recursive: true })
  await mkdir(resolve(directory, '.next/static'), { recursive: true })
  await mkdir(resolve(directory, 'public'), { recursive: true })
  await writeFile(resolve(directory, '.next/standalone/server.js'), 'server')
  await writeFile(resolve(directory, '.next/static/app.js'), 'static')
  await writeFile(resolve(directory, 'public/logo.txt'), 'public')
}

describe('E-06 e E-07: a execução deixa um relato que a pessoa consegue ler', () => {
  it('grava o relato ao lado da execução e o registra como evidência do tipo diff', async () => {
    // `kind: 'diff'` existia no esquema e NENHUM código o produzia: era um
    // valor morto. E o `pipeline.log` era gravado e nunca renderizado, então a
    // pessoa terminava com um código em inglês e nada mais.
    const f = await fixture()
    await f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })
    const run = f.runs.at(-1)!
    const raw = await readFile(resolve(run.run_directory, 'run-report.json'), 'utf8')
    const report = JSON.parse(raw) as {
      stages: { step: string; label: string; state: string; detail: string }[]
      files: { path: string; author: string; change: string; lines: number }[]
      findings: string[]
      correction: string | null
      attempt: number
    }
    expect(report.stages.map(stage => stage.step)).toEqual(['install', 'build', 'test', 'e2e'])
    for (const stage of report.stages) expect(stage.label, stage.step).not.toBe(stage.step)
    // Os arquivos que a pessoa recebeu, e quem escreveu cada um.
    expect(report.files.length).toBeGreaterThan(0)
    expect(report.files.some(file => file.author === 'model')).toBe(true)
    expect(report.files.every(file => file.change === 'added')).toBe(true)
    expect(report.correction).toBe(null)
    expect(f.evidence.some(item => item.kind === 'diff' && item.relative_path.endsWith('run-report.json'))).toBe(true)
  })

  it('na retentativa o relato mostra o que foi pedido para corrigir', async () => {
    const f = await fixture()
    let calls = 0
    const generator: CodeGeneratorPort = {
      generate: vi.fn(async () => {
        calls += 1
        if (calls === 1) throw new Error('JSON inválido')
        return cleanGeneration
      }),
    }
    await f.pipeline.run(actor, 'project', generator)
    const directories = [...new Set(f.runs.map(run => run.run_directory))].filter(value => value !== 'not-created')
    const reports = await Promise.all(directories.map(async directory =>
      JSON.parse(await readFile(resolve(directory, 'run-report.json'), 'utf8')) as { attempt: number; correction: string | null }))
    // A primeira tentativa não tinha nada a corrigir; a segunda carrega o
    // motivo real da anterior, e não uma frase genérica.
    expect(reports.find(report => report.attempt === 1)?.correction).toBe(null)
    expect(reports.find(report => report.attempt === 2)?.correction).toBe('JSON inválido')
  })
})

describe('E-11: a parada de emergência alcança o pipeline', () => {
  it('escopo parado não começa execução: nada é lido, nada é gravado, nada transita', async () => {
    const f = await fixture({
      emergencyStop: {
        assertRunning() {
          const error = new Error('O Studio está parado por uma parada de emergência.') as Error & { code?: string }
          error.code = 'STOPPED'
          throw error
        },
      },
    })
    const generator = { generate: vi.fn(async () => cleanGeneration) }
    await expect(f.pipeline.run(actor, 'project', generator)).rejects.toMatchObject({ code: 'STOPPED' })
    // A recusa é a PRIMEIRA linha: nem o projeto foi lido, e por isso nenhuma
    // execução pendente sobra para a próxima pessoa entender.
    expect(f.service.project).not.toHaveBeenCalled()
    expect(f.runs).toEqual([])
    expect(f.transitions).toEqual([])
    expect(generator.generate).not.toHaveBeenCalled()
  })

  it('a parada de OUTRO escopo não impede esta execução', async () => {
    const f = await fixture({
      emergencyStop: {
        assertRunning(scope) {
          if (scope.orgId === 'org-b') throw new Error('parado')
        },
      },
    })
    const generator = { generate: vi.fn(async () => cleanGeneration) }
    await f.pipeline.run(actor, 'project', generator)
    expect(generator.generate).toHaveBeenCalled()
  })
})
