import { lstat, mkdtemp, mkdir, readFile, rm, symlink, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import { afterEach, describe, expect, it, vi } from 'vitest'
import type { AppSpecV1 } from '../src/appspec.js'
import { createDesignSpec } from '../src/design.js'
import type { StudioPlan, StudioRun } from '../src/model.js'
import { PromptToAppPipeline, type CodeGeneratorPort } from '../src/pipeline.js'
import { BuilderLifecycleError, type BuildStep, type BuilderLifecycleFinished, type BuilderLifecycleResolverPort, type BuilderLifecycleSession, type BuilderLifecycleStepResult } from '../src/builder-lifecycle.js'
import { PromptToAppError, type PromptToAppActor, type PromptToAppService } from '../src/service.js'

const actor: PromptToAppActor = { userId: 'owner', orgId: 'org-a', tenantId: 'tenant-a', role: 'owner' }
const spec: AppSpecV1 = {
  schema_version: 1, problem: 'Apresentar serviços.', audience: 'Clientes', journeys: ['Conhecer serviços'],
  pages: [{ name: 'Início', sections: ['Serviços'] }], entities: [], sensitive_data: { detected: [], confirmed_by_user: false },
  accessibility: { wcag_level: 'AA', keyboard_required: true, reduced_motion: true }, language: 'pt-BR',
  acceptance_criteria: ['A página tem um título.'],
}
const plan: StudioPlan = {
  plan_id: 'plan', spec_id: 'spec', project_id: 'project', org_id: actor.orgId, tenant_id: actor.tenantId,
  slices: [{ slice_id: 'slice', title: 'Página', description: 'Criar página', acceptance_criteria: ['Compila'], planned_files: ['content/app.json', 'src/GeneratedApp.tsx'] }],
  status: 'APPROVED', created_at: '2026-09-03T12:00:00.000Z', updated_at: '2026-09-03T12:00:00.000Z',
}
const cleanGeneration = {
  files: [
    { path: 'content/app.json', content: '{"title":"Aurora","description":"Serviços"}' },
    { path: 'src/GeneratedApp.tsx', content: 'export default function GeneratedApp(){ return <main><h1>Início</h1><h2>Serviços</h2></main> }' },
  ], route: 'ollama', model: 'qwen', inputTokens: 10, outputTokens: 20,
} as const
const roots: string[] = []
afterEach(async () => Promise.all(roots.splice(0).map(root => rm(root, { recursive: true, force: true }))))

interface FixtureExecutionResult { readonly exitCode: number; readonly stdout: string; readonly stderr: string; readonly timedOut: boolean; readonly outputLimitExceeded?: boolean }
interface FixtureOptions {
  readonly preflight?: 'OK' | 'BLOCKED_EXTERNAL'
  readonly execute?: (directory: string, command: string) => Promise<FixtureExecutionResult>
  readonly finish?: BuilderLifecycleSession['finish']
}

async function fixture(options: FixtureOptions = {}) {
  const root = await mkdtemp(join(tmpdir(), 'dz23-pipeline-test-')); roots.push(root)
  const templateDirectory = resolve(root, 'template'); const runsRoot = resolve(root, 'runs')
  await mkdir(resolve(templateDirectory, 'src'), { recursive: true })
  await writeFile(resolve(templateDirectory, 'package.json'), '{"private":true}')
  await writeFile(resolve(templateDirectory, 'src/App.tsx'), 'export default function App(){ return null }')
  await writeFile(resolve(templateDirectory, 'next-env.d.ts'), '/// generated by Next.js')
  let state = 'PLAN_APPROVED'
  const runs: StudioRun[] = []; const transitions: string[] = []; const evidence: unknown[] = []
  const service = {
    project: vi.fn(() => ({ state, category: 'landing-page' })), plan: vi.fn(() => plan), latestSpec: vi.fn(() => ({ app_spec: spec })),
    designOrDefault: vi.fn(() => createDesignSpec({ preset: 'modern' })),
    transition: vi.fn(async (_actor, _projectId, to: string) => { state = to; transitions.push(to); return { state } }),
    putRun: vi.fn(async (_actor, run: StudioRun) => { runs.push(run) }),
    putEvidence: vi.fn(async (_actor, item: unknown) => { evidence.push(item) }),
  }
  const executeImplementation: NonNullable<FixtureOptions['execute']> = options.execute ?? (async (): Promise<FixtureExecutionResult> => ({ exitCode: 0, stdout: 'ok', stderr: '', timedOut: false }))
  const execute = vi.fn(executeImplementation)
  let preparedDirectory = ''; let buildState: 'PREPARED' | 'INSTALL_OK' | 'BUILD_OK' | 'TEST_OK' | 'E2E_OK' | 'FAILED' | 'CANCELLED' = 'PREPARED'
  const builder: BuilderLifecycleSession = {
    preflight: vi.fn(async () => options.preflight === 'BLOCKED_EXTERNAL'
      ? { state: 'BLOCKED_EXTERNAL' as const }
      : { state: 'OK' as const }),
    prepare: vi.fn(async directory => { preparedDirectory = directory; buildState = 'PREPARED'; return { buildRef: 'build_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' } }),
    execute: vi.fn(async (_buildRef: string, step: BuildStep) => {
      const command = ({ install: 'pnpm install --offline', build: 'pnpm run build', test: 'pnpm run test', e2e: 'pnpm run test:e2e' } as const)[step]
      const result = await execute(preparedDirectory, command)
      buildState = result.exitCode === 0 ? ({ install: 'INSTALL_OK', build: 'BUILD_OK', test: 'TEST_OK', e2e: 'E2E_OK' } as const)[step] : 'FAILED'
      return { state: buildState, step, result: { exit_code: result.exitCode, stdout: result.stdout, stderr: result.stderr, timed_out: result.timedOut, termination_reason: result.outputLimitExceeded === true ? 'output_limit' as const : result.timedOut ? 'timeout' as const : null, output_limit_exceeded: result.outputLimitExceeded === true } }
    }),
    cancel: vi.fn(async () => { buildState = 'CANCELLED' }),
    finish: vi.fn(options.finish ?? (async () => ({ finalState: buildState === 'E2E_OK' ? 'E2E_OK' as const : buildState === 'CANCELLED' ? 'CANCELLED' as const : 'FAILED' as const, exported: buildState === 'E2E_OK' ? { relative_path: 'exports/build_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', sha256: 'a'.repeat(64), files: 1, bytes: 1 } : null, cleanupPending: false, cleaned: true }))),
    listManaged: vi.fn(async () => []),
  }
  const resolver: BuilderLifecycleResolverPort<PromptToAppActor> = { forActor: vi.fn(async () => builder) }
  let id = 0
  const pipeline = new PromptToAppPipeline({
    service: service as unknown as PromptToAppService, builder: resolver,
    templateDirectory, runsRoot, now: () => new Date('2026-09-03T12:00:00.000Z'), createId: () => `id-${++id}`,
  })
  return { pipeline, service, builder, resolver, execute, runs, transitions, evidence, templateDirectory, runsRoot }
}

describe('Prompt-to-App pipeline', () => {
  it.skipIf(process.platform === 'win32')('rejects a template symlink before creating a run or changing project state', async () => {
    const f = await fixture(); const outside = await mkdtemp(join(tmpdir(), 'dz23-template-outside-')); roots.push(outside)
    await symlink(outside, resolve(f.templateDirectory, 'linked'), 'dir')
    const generator = { generate: vi.fn(async () => cleanGeneration) }
    await expect(f.pipeline.run(actor, 'project', generator)).rejects.toThrow('Link simbólico')
    expect(generator.generate).not.toHaveBeenCalled()
    expect(f.runs).toEqual([])
    expect(f.transitions).toEqual([])
  })

  it('does not promote supervisor success while the authenticated exported acceptance report is unavailable', async () => {
    const f = await fixture(); const generator = { generate: vi.fn(async () => cleanGeneration) }
    const result = await f.pipeline.run(actor, 'project', generator)
    expect(result).toMatchObject({ state: 'BLOCKED_EXTERNAL', attempts: 1 })
    expect(f.transitions).toEqual(['GENERATING', 'INTERRUPTED'])
    expect(f.execute).toHaveBeenCalledTimes(4)
    expect(f.resolver.forActor).toHaveBeenCalledOnce()
    expect(f.runs.at(-1)).toMatchObject({ stage: 'verify', state: 'BLOCKED_EXTERNAL', failure_code: 'ACCEPTANCE_ATTESTATION_UNAVAILABLE', artifact_sha256: null })
    expect(f.runs.some(run => run.state === 'PASSED')).toBe(false)
    expect(f.runs.flatMap(run => run.acceptance_checks).some(check => check.status === 'PENDING')).toBe(true)
    expect(f.runs.at(-1)).toMatchObject({ operation_id: expect.any(String), owner_session_id: 'direct-execution' })
    expect(f.evidence).toHaveLength(0)
  })

  it('rejects hostile operation identifiers before creating a run path', async () => {
    const f = await fixture(); const escaped = resolve(f.runsRoot, '..', 'escaped')
    await expect(f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) }, { operationId: '../escaped' })).rejects.toMatchObject({ code: 'INVALID' })
    await expect(lstat(escaped)).rejects.toMatchObject({ code: 'ENOENT' })
    expect(f.runs).toEqual([])
    expect(f.transitions).toEqual([])
  })

  it.each([
    ['missing checks', '{}'],
    ['invalid JSON', '{'],
    ['empty checks', '{"schema_version":1,"checks":[]}'],
  ])('fails closed when the AppSpec report has %s', async (_case, content) => {
    const f = await fixture({ execute: async (directory, command) => {
      if (command === 'pnpm run test:e2e') await writeFile(resolve(directory, 'evidence/appspec-report.json'), content)
      return { exitCode: 0, stdout: 'ok', stderr: '', timedOut: false }
    } })
    await expect(f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })).resolves.toMatchObject({ state: 'TESTS_FAILED' })
    expect(f.runs.some(run => run.state === 'PASSED')).toBe(false)
    expect(f.transitions).not.toContain('VERIFIED_PROTOTYPE')
    expect(f.runs.at(-1)).toMatchObject({ state: 'FAILED', failure_code: 'APPSPEC_REPORT_INVALID' })
  })

  it('never records PASS when finish cannot prove cleanup', async () => {
    const f = await fixture({ execute: async (directory, command) => {
      if (command === 'pnpm run test:e2e') await passAcceptance(directory)
      return { exitCode: 0, stdout: 'ok', stderr: '', timedOut: false }
    }, finish: async () => ({ finalState: 'E2E_OK', exported: { relative_path: 'exports/build_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', sha256: 'a'.repeat(64), files: 1, bytes: 1 }, cleanupPending: true, cleaned: false }) })
    await expect(f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })).resolves.toMatchObject({ state: 'BLOCKED_EXTERNAL', attempts: 1 })
    expect(f.runs.at(-1)).toMatchObject({ state: 'BLOCKED_EXTERNAL', failure_code: 'FINISH_INCONCLUSIVE', artifact_sha256: null })
    expect(f.transitions).toEqual(['GENERATING', 'INTERRUPTED'])
    expect(f.service.project()).toMatchObject({ state: 'INTERRUPTED' })
  })

  it('terminalizes an unexpected test-process failure without leaving GENERATING', async () => {
    const f = await fixture({ execute: async (directory, command) => {
      if (command === 'pnpm run build') await writeRuntimeOutput(directory)
      if (command === 'pnpm run test') throw new Error('subprocess-channel-lost')
      return { exitCode: 0, stdout: 'ok', stderr: '', timedOut: false }
    } })
    await expect(f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })).resolves.toMatchObject({ state: 'TESTS_FAILED' })
    expect(f.runs.at(-1)).toMatchObject({ state: 'FAILED', stage: 'test', failure_code: 'PIPELINE_UNEXPECTED_FAILURE' })
    expect(f.transitions).toEqual(['GENERATING', 'BUILD_OK', 'TESTS_FAILED'])
  })

  it('records an inconclusive lifecycle channel as interrupted instead of a logical build failure', async () => {
    const f = await fixture()
    f.builder.execute = vi.fn(async () => { throw new BuilderLifecycleError('INTERRUPTED', 'INVALID_STEP_ORDER') })
    const result = await f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })
    expect(result).toMatchObject({ state: 'INTERRUPTED', attempts: 1 })
    expect(f.runs.at(-1)).toMatchObject({ state: 'FAILED', failure_code: 'INVALID_STEP_ORDER', artifact_sha256: null })
    expect(f.transitions).toEqual(['GENERATING', 'INTERRUPTED'])
  })

  it('does not trust a locally forged PASSED report as exported evidence', async () => {
    const f = await fixture()
    const execute: BuilderLifecycleSession['execute'] = async (_buildRef: string, step: BuildStep): Promise<BuilderLifecycleStepResult> => {
      if (step === 'e2e') await passAcceptance(resolve(f.runsRoot, 'id-1'))
      return { state: ({ install: 'INSTALL_OK', build: 'BUILD_OK', test: 'TEST_OK', e2e: 'E2E_OK' } as const)[step], step, result: { exit_code: 0, stdout: '', stderr: '', timed_out: false, termination_reason: null, output_limit_exceeded: false } }
    }
    const finish: BuilderLifecycleSession['finish'] = async (): Promise<BuilderLifecycleFinished> => ({ finalState: 'E2E_OK', exported: { relative_path: 'exports/build_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', sha256: 'a'.repeat(64), files: 1, bytes: 1 }, cleanupPending: false, cleaned: true })
    f.builder.execute = vi.fn(execute)
    f.builder.finish = vi.fn(finish)
    await expect(f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })).resolves.toMatchObject({ state: 'BLOCKED_EXTERNAL' })
    expect(f.runs.at(-1)).toMatchObject({ state: 'BLOCKED_EXTERNAL', stage: 'verify', failure_code: 'ACCEPTANCE_ATTESTATION_UNAVAILABLE', artifact_sha256: null })
    expect(f.transitions).toEqual(['GENERATING', 'INTERRUPTED'])
    expect(f.transitions).not.toContain('VERIFIED_PROTOTYPE')
  })

  it('rejects an oversized acceptance report before parsing it', async () => {
    const f = await fixture({ execute: async (directory, command) => {
      if (command === 'pnpm run test:e2e') await writeFile(resolve(directory, 'evidence/appspec-report.json'), ' '.repeat(1024 * 1024 + 1))
      return { exitCode: 0, stdout: 'ok', stderr: '', timedOut: false }
    } })
    await expect(f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })).resolves.toMatchObject({ state: 'TESTS_FAILED' })
    expect(f.runs.at(-1)).toMatchObject({ state: 'FAILED', failure_code: 'APPSPEC_REPORT_TOO_LARGE' })
  })

  it('does not retry a process that exceeds the output budget', async () => {
    const f = await fixture({ execute: async () => ({
      exitCode: -1, stdout: 'bounded', stderr: '', timedOut: false,
      terminationReason: 'output_limit' as const, outputLimitExceeded: true,
    }) })
    await expect(f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })).resolves.toMatchObject({ state: 'BUILD_FAILED', attempts: 1 })
    expect(f.execute).toHaveBeenCalledTimes(1)
    expect(f.runs.at(-1)).toMatchObject({ state: 'FAILED', failure_code: 'PROCESS_OUTPUT_LIMIT_EXCEEDED' })
  })

  it('allows only the framework-generated next-env file to change during build', async () => {
    const f = await fixture({ execute: async (directory, command) => {
      if (command === 'pnpm run build') { await writeRuntimeOutput(directory); await writeFile(resolve(directory, 'next-env.d.ts'), '/// regenerated by Next.js') }
      if (command === 'pnpm run test:e2e') await passAcceptance(directory)
      return { exitCode: 0, stdout: 'ok', stderr: '', timedOut: false }
    } })
    await expect(f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })).resolves.toMatchObject({ state: 'BLOCKED_EXTERNAL' })
  })

  it('rejects a build that changes another protected template file', async () => {
    const f = await fixture({ execute: async (directory, command) => {
      if (command === 'pnpm run build') { await writeRuntimeOutput(directory); await writeFile(resolve(directory, 'src/App.tsx'), 'tampered') }
      if (command === 'pnpm run test:e2e') await passAcceptance(directory)
      return { exitCode: 0, stdout: 'ok', stderr: '', timedOut: false }
    } })
    await expect(f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })).resolves.toMatchObject({ state: 'BUILD_FAILED', message: 'TEMPLATE_INTEGRITY_FAILED' })
  })

  it('distinguishes a test failure from a build failure after three attempts', async () => {
    const f = await fixture({ execute: async (_directory, command) => ({ exitCode: command === 'pnpm run test' ? 1 : 0, stdout: '', stderr: '', timedOut: false }) })
    const result = await f.pipeline.run(actor, 'project', { generate: vi.fn(async () => cleanGeneration) })
    expect(result).toMatchObject({ state: 'TESTS_FAILED', attempts: 3 })
    expect(f.transitions).toEqual(['GENERATING', 'BUILD_OK', 'TESTS_FAILED'])
    const failures = f.runs.filter(run => run.state === 'FAILED')
    expect(failures).toHaveLength(3)
    expect(failures.every(run => run.stage === 'test' && run.failure_code === 'test: exit 1')).toBe(true)
    expect(failures.every(run => run.artifact_sha256 == null)).toBe(true)
  })

  it('retries rejected model output with the prior diagnostic and closes as build failed', async () => {
    const f = await fixture()
    const generator: CodeGeneratorPort = { generate: vi.fn(async (_spec, _plan, diagnostic) => { throw new Error(diagnostic === undefined ? 'JSON inválido' : diagnostic) }) }
    const result = await f.pipeline.run(actor, 'project', generator)
    expect(result).toMatchObject({ state: 'BUILD_FAILED', attempts: 3, message: 'JSON inválido' })
    expect(generator.generate).toHaveBeenNthCalledWith(2, spec, plan, 'JSON inválido')
    expect(f.execute).not.toHaveBeenCalled()
    const failures = f.runs.filter(run => run.state === 'FAILED')
    expect(failures).toHaveLength(3)
    expect(failures.every(run => run.stage === 'generate' && run.failure_code === 'JSON inválido')).toBe(true)
    expect(f.transitions).toEqual(['GENERATING', 'BUILD_FAILED'])
  })

  it('rejects forbidden imports before writing or running builder commands', async () => {
    const f = await fixture()
    const generator = { generate: vi.fn(async () => ({
      ...cleanGeneration,
      files: [{ path: 'src/GeneratedApp.tsx', content: "import { readFile } from 'node:fs'; export default function App(){ return null }; void readFile" }],
    })) }
    const result = await f.pipeline.run(actor, 'project', generator)
    expect(result).toMatchObject({ state: 'BUILD_FAILED', attempts: 3 })
    expect(result.message).toContain('node:fs')
    expect(f.execute).not.toHaveBeenCalled()
    expect(f.runs.filter(run => run.state === 'FAILED')).toHaveLength(3)
  })

  it('rejects a real personal identifier embedded in the AppSpec before preflight or generation', async () => {
    const f = await fixture()
    const unsafeSpec: AppSpecV1 = {
      ...spec,
      entities: [{ name: 'Cadastro', kind: 'database', sensitive: false, fields: [
        { name: 'Tipo', type: 'selection', required: true, options: ['CPF 529.982.247-25'] },
      ] }],
    }
    f.service.project.mockImplementation(() => ({ state: 'PLAN_APPROVED', category: 'form-database' }))
    f.service.latestSpec.mockReturnValue({ app_spec: unsafeSpec })
    const generator = { generate: vi.fn(async () => cleanGeneration) }
    await expect(f.pipeline.run(actor, 'project', generator)).rejects.toMatchObject({ code: 'INVALID' })
    expect(f.builder.preflight).not.toHaveBeenCalled()
    expect(generator.generate).not.toHaveBeenCalled()
    expect(f.runs).toHaveLength(0)
  })

  it('blocks before generation when the isolated builder is unavailable', async () => {
    const f = await fixture({ preflight: 'BLOCKED_EXTERNAL' }); const generator = { generate: vi.fn(async () => cleanGeneration) }
    await expect(f.pipeline.run(actor, 'project', generator)).resolves.toEqual({ state: 'BLOCKED_EXTERNAL', attempts: 0, message: 'O ambiente isolado para criar seu projeto não está disponível neste computador.' })
    expect(generator.generate).not.toHaveBeenCalled()
    expect(f.transitions).toEqual([])
    expect(f.runs.at(-1)).toMatchObject({ stage: 'build', state: 'BLOCKED_EXTERNAL', sandbox: 'unavailable', artifact_sha256: null, failure_code: 'BUILDER_UNAVAILABLE' })
    await expect(lstat(f.runsRoot)).rejects.toMatchObject({ code: 'ENOENT' })
  })

  it('refuses to start without the approved plan and approved project state', async () => {
    const f = await fixture()
    f.service.plan.mockReturnValueOnce({ ...plan, status: 'PROPOSED' })
    await expect(f.pipeline.run(actor, 'project', { generate: vi.fn() })).rejects.toBeInstanceOf(PromptToAppError)
    expect(f.builder.preflight).not.toHaveBeenCalled()
  })

  it('records cancellation against the owning browser session before the next builder step', async () => {
    const controller = new AbortController()
    const f = await fixture({ execute: async () => { controller.abort('cancelled-by-user'); return { exitCode: 0, stdout: '', stderr: '', timedOut: false } } })
    const result = await f.pipeline.run({ ...actor, sessionId: 'browser-session' }, 'project', { generate: vi.fn(async () => cleanGeneration) }, { operationId: 'operation', ownerSessionId: 'browser-session', signal: controller.signal })
    expect(result).toMatchObject({ state: 'CANCELLED', attempts: 1 })
    expect(f.runs.at(-1)).toMatchObject({ run_id: 'operation', operation_id: 'operation', owner_session_id: 'browser-session', state: 'CANCELLED', artifact_sha256: null })
    expect(f.transitions).toEqual(['GENERATING', 'CANCELLED'])
    expect(f.builder.cancel).toHaveBeenCalledOnce()
    expect(f.builder.finish).toHaveBeenCalledOnce()
  })
})

async function passAcceptance(directory: string): Promise<void> {
  const reportPath = resolve(directory, 'evidence/appspec-report.json')
  const report = JSON.parse(await readFile(reportPath, 'utf8')) as { checks: Array<{ status: string }> }
  report.checks = report.checks.map(check => check.status === 'PENDING' ? { ...check, status: 'PASSED' } : check)
  await writeFile(reportPath, JSON.stringify(report))
}

async function writeRuntimeOutput(directory: string): Promise<void> {
  await mkdir(resolve(directory, '.next/standalone'), { recursive: true })
  await mkdir(resolve(directory, '.next/static'), { recursive: true })
  await mkdir(resolve(directory, 'public'), { recursive: true })
  await writeFile(resolve(directory, '.next/standalone/server.js'), 'server')
  await writeFile(resolve(directory, '.next/static/app.js'), 'static')
  await writeFile(resolve(directory, 'public/logo.txt'), 'public')
}
